services:
  db:
    image: postgres:15-alpine
    container_name: pkmscan-db
    restart: always
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    container_name: pkmscan-cache
    restart: always

  api:
    build: ./services/api_gateway
    container_name: pkmscan-api
    volumes:
      - ./services/api_gateway:/app
      - ./aws_shared:/app/aws_shared
      - ~/.aws:/root/.aws
    env_file:
      - .env
    environment:
      - AWS_PROFILE=${AWS_PROFILE_WEB}
      - AWS_REGION_NAME=${AWS_REGION_NAME}
      - AWS_STORAGE_BUCKET=${AWS_STORAGE_BUCKET}
      - AWS_QUEUE_URL=${AWS_QUEUE_URL}
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
    depends_on:
      - db
      - redis
    ports:
      - "8000:8000"

  processor:
    build: ./services/img_processor
    container_name: pkmscan-processor
    volumes:
      - ./services/img_processor:/app
      - ./aws_shared:/app/aws_shared
      - ~/.aws:/root/.aws
    env_file:
      - .env
    environment:
      - AWS_PROFILE=${AWS_PROFILE_PROCESSOR}
      - AWS_REGION_NAME=${AWS_REGION_NAME}
      - AWS_STORAGE_BUCKET=${AWS_STORAGE_BUCKET}
      - AWS_QUEUE_URL=${AWS_QUEUE_URL}
    depends_on:
      - redis

volumes:
  postgres_data:
