name: PKMScan CI - Processor Tests

on:
  push:
    branches: [ "**" ] # Runs on every branch
  pull_request:
    branches: [ "main" ] # Runs when merging to main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and Run Tests
        run: |
          docker compose run --rm processor python3 -m unittest discover tests